# Generated by Django 4.0.3 on 2023-09-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_alter_student_student_id_book_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
