# Generated by Django 4.0.3 on 2023-10-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_category_bookreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
