# Generated by Django 4.0.3 on 2023-10-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bookrequest_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreturn',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
