# Generated by Django 4.0.3 on 2023-10-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_staff_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='student',
            name='mat_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
